/* This file was generated by SableCC (http://www.sablecc.org/). */

package hw3.node;

import hw3.analysis.*;

@SuppressWarnings("nls")
public final class ADivTerm extends PTerm
{
    private PTerm _left_;
    private TSlash _slash_;
    private PAtom _right_;

    public ADivTerm()
    {
        // Constructor
    }

    public ADivTerm(
        @SuppressWarnings("hiding") PTerm _left_,
        @SuppressWarnings("hiding") TSlash _slash_,
        @SuppressWarnings("hiding") PAtom _right_)
    {
        // Constructor
        setLeft(_left_);

        setSlash(_slash_);

        setRight(_right_);

    }

    @Override
    public Object clone()
    {
        return new ADivTerm(
            cloneNode(this._left_),
            cloneNode(this._slash_),
            cloneNode(this._right_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADivTerm(this);
    }

    public PTerm getLeft()
    {
        return this._left_;
    }

    public void setLeft(PTerm node)
    {
        if(this._left_ != null)
        {
            this._left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._left_ = node;
    }

    public TSlash getSlash()
    {
        return this._slash_;
    }

    public void setSlash(TSlash node)
    {
        if(this._slash_ != null)
        {
            this._slash_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._slash_ = node;
    }

    public PAtom getRight()
    {
        return this._right_;
    }

    public void setRight(PAtom node)
    {
        if(this._right_ != null)
        {
            this._right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._right_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._left_)
            + toString(this._slash_)
            + toString(this._right_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._left_ == child)
        {
            this._left_ = null;
            return;
        }

        if(this._slash_ == child)
        {
            this._slash_ = null;
            return;
        }

        if(this._right_ == child)
        {
            this._right_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._left_ == oldChild)
        {
            setLeft((PTerm) newChild);
            return;
        }

        if(this._slash_ == oldChild)
        {
            setSlash((TSlash) newChild);
            return;
        }

        if(this._right_ == oldChild)
        {
            setRight((PAtom) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
