/* This file was generated by SableCC (http://www.sablecc.org/). */

package hw3.node;

import hw3.analysis.*;

@SuppressWarnings("nls")
public final class ASomeExprList extends PExprList
{
    private PExpr _first_;
    private PExprList _rest_;

    public ASomeExprList()
    {
        // Constructor
    }

    public ASomeExprList(
        @SuppressWarnings("hiding") PExpr _first_,
        @SuppressWarnings("hiding") PExprList _rest_)
    {
        // Constructor
        setFirst(_first_);

        setRest(_rest_);

    }

    @Override
    public Object clone()
    {
        return new ASomeExprList(
            cloneNode(this._first_),
            cloneNode(this._rest_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASomeExprList(this);
    }

    public PExpr getFirst()
    {
        return this._first_;
    }

    public void setFirst(PExpr node)
    {
        if(this._first_ != null)
        {
            this._first_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._first_ = node;
    }

    public PExprList getRest()
    {
        return this._rest_;
    }

    public void setRest(PExprList node)
    {
        if(this._rest_ != null)
        {
            this._rest_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rest_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._first_)
            + toString(this._rest_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._first_ == child)
        {
            this._first_ = null;
            return;
        }

        if(this._rest_ == child)
        {
            this._rest_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._first_ == oldChild)
        {
            setFirst((PExpr) newChild);
            return;
        }

        if(this._rest_ == oldChild)
        {
            setRest((PExprList) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
